server:
  port: 8090
spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/ump
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
  redis:
    host: localhost
acsEndpoint: http://10.84.20.138:7557

