server:
  port: 8090
spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/ump
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  redis:
    host: localhost
acsEndpoint: http://localhost:7557